add_library(likwid INTERFACE)
if (LIKWID)
  find_library(LIKWID_LIB likwid HINTS ${LIKWID}/lib)
  message("LIKWID_LIB " ${LIKWID_LIB})
  target_link_libraries(likwid INTERFACE ${LIKWID_LIB})
  find_path(LIKWID_INC likwid.h HINTS ${LIKWID}/include)
  message("LIKWID_INC " ${LIKWID_INC})
  target_include_directories(likwid INTERFACE ${LIKWID_INC})
  target_compile_definitions(likwid INTERFACE -DLIKWID_PERFMON)
endif (LIKWID)
