add_library(likwid INTERFACE)
if (LIKW)
  find_library(LIKW_LIB likwid HINTS ${LIKW}/lib)
  message("LIKW_LIB " ${LIKW_LIB})
  target_link_libraries(likwid INTERFACE ${LIKW_LIB})
  find_path(LIKW_INC likwid.h HINTS ${LIKW}/include)
  message("LIKW_INC " ${LIKW_INC})
  target_include_directories(likwid INTERFACE ${LIKW_INC})
  target_compile_definitions(likwid INTERFACE -DLIKWID_PERFMON)
endif (LIKW)
