add_library(simh INTERFACE)
if (SIMH)
  find_path(SIMP "hpe_sim_api_linux64.h" PATHS ${SIMH})
  message(STATUS "SIMP => ${SIMP}")
  if (NOT(SIMP STREQUAL "SIMP-NOTFOUND"))
    target_include_directories(simh INTERFACE ${SIMH})
    target_compile_definitions(simh INTERFACE -DHAVE_ZHPE_SIM)
  endif (NOT(SIMP STREQUAL "SIMP-NOTFOUND"))
endif (SIMH)
